name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: Whether to execute cache step
        default: true
      node-version:
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
        default: 22.x
        description: Node version

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      CACHE_KEY: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: 13-caching/react-app/node_modules
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
  linting:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.install-deps.outputs.CACHE_KEY }}
          path: 13-caching/react-app/node_modules
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    needs:
      - install-deps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4
        with:
         key: ${{ needs.install-deps.outputs.CACHE_KEY }}
         path: 13-caching/react-app/node_modules
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying
        run: |
          echo "Deploying to nonprod"