name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to ping"
        default: 'https://www.google.com'
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://www.abxzy.com'
          - 'invalid-aajhsdsldhlhl'
      max_trials:
        description: 'Maximum trials until action fails'
        default: '10'
        type: string
      delay:
        description: 'Delay in seconds between trials'
        default: '5'
        type: string

run-name: 17 - 3 - Custom Actions - Docker | URL - ${{ inputs.url }}

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
         url: ${{ inputs.url }}
         delay: ${{ inputs.delay }}
         max_trials: ${{ inputs.max_trials }}
      - name: Print output from ping url
        run: |
          echo "URL reachable: ${{ steps.ping-url.outputs.url-reachable }}"