name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
     target-directory: .
  e2e-tests:
    needs:
      - deploy
    uses: Kartik9555/github-actions-course-example-e2e/.github/workflows/e2e.yaml@8d68bb8bd4ff2bc117fdc2b3678f9733411b743c
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}
