name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  mandatory:
    runs-on: ubuntu-latest
    steps:
      - name: Make the repo private for the workflow to run
        run: |
          echo "Check the step name"
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
     target-directory: .
  e2e-tests:
    needs:
      - deploy
    uses: Kartik9555/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}
